[project]
name = "dismissal-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.17.2",
    "fastapi[standard]>=0.119.0",
    "pwdlib[argon2]>=0.2.1",
    "pyjwt>=2.10.1",
    "pytest>=8.4.2",
    "sqlalchemy>=2.0.44",
    "taskipy>=1.14.1",
]
